"""ART (openpipe-art) RL adapter: write a runnable training script, then say what to run.

`submit` vendors `touchstone/checks/{dsl,run}.py` next to a generated `art_train.py` (the same
vendoring trick `bench/harbor_export` uses, so the script depends on neither the network nor the
installed `touchstone` package), then raises `InfraRequired` — Touchstone never spends GPUs itself.
The script loads `rl_tasks.jsonl`, and its rollout replays each task through an `art.TrainableModel`
and scores the reply with the task's vendored checks as the reward.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from .datasets import DatasetBundle, atomic_write
from .trainer import InfraRequired, JobHandle, TrainConfig

_CHECKS_SRC = Path(__file__).resolve().parent.parent / "checks"

ART_SCRIPT = '''\
"""ART RL training for a Touchstone benchmark. Generated by `touchstone train submit --backend art`.

Run on a host with a GPU:  pip install openpipe-art  &&  python art_train.py
The reward is the task's own checks (vendored under ./touchstone_checks), so training optimizes the
exact behaviour Touchstone's stakeholders agreed on.
"""

import asyncio
import json
from pathlib import Path

import art  # pip install openpipe-art

from touchstone_checks.dsl import Check, Target
from touchstone_checks.run import evaluate, passes

HERE = Path(__file__).resolve().parent
BASE_MODEL = "{base_model}"
STEPS = {steps}


def load_tasks():
    with (HERE / "rl_tasks.jsonl").open() as fh:
        return [json.loads(line) for line in fh if line.strip()]


def score(task, content, tool_calls):
    checks = [Check.from_dict(c) for c in task["checks"]]
    target = Target(output_text=content or "", tool_calls=tool_calls or [],
                    reference=task.get("reference"))
    results = evaluate(checks, target, judge_provider=None)
    return 1.0 if passes(results, checks) else 0.0


async def rollout(model: art.Model, task: dict) -> art.Trajectory:
    messages = list(task["messages"])
    completion = await model.openai_client().chat.completions.create(
        model=model.name, messages=messages, tools=task.get("tools") or None,
    )
    choice = completion.choices[0].message
    tool_calls = [{{"name": tc.function.name, "arguments": tc.function.arguments}}
                  for tc in (choice.tool_calls or [])]
    reward = score(task, choice.content, tool_calls)
    return art.Trajectory(messages_and_choices=messages + [choice], reward=reward)


async def main():
    model = art.TrainableModel(name="touchstone-rl", project="touchstone", base_model=BASE_MODEL)
    await model.register(art.LocalBackend())
    tasks = load_tasks()
    for _ in range(STEPS):
        groups = await art.gather_trajectory_groups(
            art.TrajectoryGroup(rollout(model, t) for t in tasks)
        )
        await model.train(groups)


if __name__ == "__main__":
    asyncio.run(main())
'''


def _vendor_checks(out_dir: Path) -> None:
    vendor = out_dir / "touchstone_checks"
    vendor.mkdir(parents=True, exist_ok=True)
    atomic_write(vendor / "__init__.py", "")
    for name in ("dsl.py", "run.py"):
        shutil.copyfile(_CHECKS_SRC / name, vendor / name)


class ArtTrainer:
    backend = "art"

    def prepare(self, conn, benchmark_id, out_dir):
        from .datasets import prepare

        return prepare(conn, benchmark_id, out_dir)

    def submit(self, bundle: DatasetBundle, config: TrainConfig) -> JobHandle:
        _vendor_checks(bundle.out_dir)
        script = bundle.out_dir / "art_train.py"
        atomic_write(script, ART_SCRIPT.format(base_model=config.base_model, steps=config.steps))
        raise InfraRequired(
            f"Wrote {script}; run `pip install openpipe-art && python {script.name}` "
            f"in {bundle.out_dir} on a host with a GPU to train."
        )
