"""TRL SFT adapter: write a config + launch command, then say what to run.

`submit` writes `trl_sft.yaml` (a `trl sft` config pointed at `sft.jsonl`) and `run_trl.sh` (the
launch command), then raises `InfraRequired`. Touchstone never spends GPUs itself; SFT on the
passing references is the warm start before preference/RL.
"""

from __future__ import annotations

from pathlib import Path

from .datasets import DatasetBundle, atomic_write
from .trainer import InfraRequired, JobHandle, TrainConfig

TRL_YAML = """\
# TRL SFT config for a Touchstone benchmark.
# Generated by `touchstone train submit --backend trl`. Run with `bash run_trl.sh`.
model_name_or_path: {base_model}
dataset_name: sft.jsonl        # {sft} rows: canonical context messages + the reference completion
dataset_text_field: messages
max_steps: {steps}
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
bf16: true
output_dir: ./trl-out
"""

RUN_SH = """\
#!/usr/bin/env bash
# Run on a host with a GPU:  pip install trl  &&  bash run_trl.sh
set -euo pipefail
cd "$(dirname "$0")"
trl sft --config trl_sft.yaml
"""


class TrlTrainer:
    backend = "trl"

    def prepare(self, conn, benchmark_id, out_dir):
        from .datasets import prepare

        return prepare(conn, benchmark_id, out_dir)

    def submit(self, bundle: DatasetBundle, config: TrainConfig) -> JobHandle:
        yaml_path = bundle.out_dir / "trl_sft.yaml"
        run_path = bundle.out_dir / "run_trl.sh"
        atomic_write(yaml_path, TRL_YAML.format(
            base_model=config.base_model, steps=config.steps, sft=bundle.counts["sft"]))
        atomic_write(run_path, RUN_SH)
        Path(run_path).chmod(0o755)
        raise InfraRequired(
            f"Wrote {yaml_path} and {run_path}; run `pip install trl && bash {run_path.name}` "
            f"in {bundle.out_dir} on a host with a GPU to train."
        )
