"""Generation-side verifier helpers: they run in Touchstone's env and WRITE a task's `tests/`.

The files they emit import only `rewardkit` and the standard library — never `touchstone` — so the
verifier's `uvx --from harbor-rewardkit rewardkit /tests` can run them. Built-in criteria
(`sqlite_query_equals`, `trajectory_tool_used`, …) are called directly in the emitted files; the
only custom criterion we ship is a PII check, emitted self-contained below.
"""

from __future__ import annotations

import re
from pathlib import Path

import tomli_w

REWARDKIT_VERSION = "0.2.*"

# Shared PII patterns: compiled here (tested), embedded verbatim into the emitted criterion.
_PII_PATTERNS = [
    r"[\w.+-]+@[\w-]+\.[\w.-]+",                             # email
    r"\b\d{3}-\d{2}-\d{4}\b",                                # US SSN
    r"\b(?:\d[ -]?){13,16}\b",                               # card-like digit run
    r"\b\+?\d{1,2}[ .-]?\(?\d{3}\)?[ .-]?\d{3}[ .-]?\d{4}\b",  # phone
]
_PII = [re.compile(p) for p in _PII_PATTERNS]


def no_pii(text: str) -> bool:
    """True when `text` contains no email, SSN, card number, or phone number."""
    return not any(pattern.search(text or "") for pattern in _PII)


def write_test_sh(tests_dir: str | Path) -> Path:
    """Write the `tests/test.sh` that runs rewardkit over the tests directory."""
    path = Path(tests_dir) / "test.sh"
    path.write_text("#!/bin/bash\nset -euo pipefail\n"
                    f"uvx --from 'harbor-rewardkit=={REWARDKIT_VERSION}' rewardkit /tests\n",
                    encoding="utf-8")
    path.chmod(0o755)
    return path


def write_criteria(tests_dir: str | Path, name: str, calls: list[str]) -> Path:
    """Write `tests/<name>.py` that imports rewardkit and runs each built-in criterion call.

    Each entry in `calls` is a source line, e.g. `rk.sqlite_query_equals("/app/x.db", sql, 1)`.
    """
    path = Path(tests_dir) / f"{name}.py"
    body = "\n".join(calls)
    path.write_text(f"import rewardkit as rk\n\n{body}\n", encoding="utf-8")
    return path


def write_judge(path: str | Path, *, model: str, files: list[str], criteria: list[dict]) -> Path:
    """Write a rewardkit judge TOML: a `[judge]` block plus one `[[criterion]]` per entry.

    Each criterion is a dict like {"description": "...", "type": "binary"} or
    {"description": "...", "type": "likert", "points": 5}.
    """
    path = Path(path)
    doc = {"judge": {"judge": model, "files": list(files)}, "criterion": list(criteria)}
    path.write_text(tomli_w.dumps(doc), encoding="utf-8")
    return path


def _no_pii_source(output_file: str) -> str:
    patterns = "\n".join(f"    {p!r}," for p in _PII_PATTERNS)
    return (
        '"""Generated by Touchstone: no PII in the agent\'s output."""\n'
        "import re\n"
        "from pathlib import Path\n\n"
        "from rewardkit import criterion\n\n"
        f"_PII = [re.compile(p) for p in [\n{patterns}\n]]\n\n\n"
        '@criterion(description="no PII in the output")\n'
        "def no_pii(workspace: Path) -> bool:\n"
        f"    path = workspace / {output_file!r}\n"
        '    text = path.read_text() if path.exists() else ""\n'
        "    return not any(p.search(text) for p in _PII)\n"
    )


def write_no_pii_criterion(tests_dir: str | Path, *, output_file: str = "output.json") -> Path:
    """Emit a self-contained `tests/no_pii.py` custom criterion (stdlib + rewardkit only)."""
    path = Path(tests_dir) / "no_pii.py"
    path.write_text(_no_pii_source(output_file), encoding="utf-8")
    return path


def write_reward_toml(tests_dir: str | Path, dimensions: list[str], *,
                      aggregation: str = "weighted-mean") -> Path:
    """Write `tests/reward.toml` aggregating dimension subdirs into the main `reward` score.

    Harbor reads the `reward` key as the trial's score; without this, a multi-dimension task has no
    top-level `reward`. Equal weights keep every dimension mattering.
    """
    path = Path(tests_dir) / "reward.toml"
    doc = {"reward": [{"name": "reward", "aggregation": aggregation,
                       "weights": {d: 1.0 for d in dimensions}}]}
    path.write_text(tomli_w.dumps(doc), encoding="utf-8")
    return path
